### ISSUE TITLE
frameset.dtd miss element "aliases" and "alias"

### ISSUE THREAD

**Issue by mlciv** [propbank/propbank-documentation#1]
In frameset.dtd, element "roleset" misses element "aliases" and "alias" e.g. eat.xml

**Comment by timjogorman** [comment]
Thanks for pointing that out!  That frameset.dtd file was out of date -- I've pushed a new version that should work with new frames. 

(Up-to-date frameset.dtd files are also usually included directly in the "frames" directory of every release, just to make sure that the xml files are released with the correct dtd file.)
